import ANON from '../anonim';

const CONSTANTES = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLERCER_SESION: 'ESTABLERCER_SESION',
  CERRAR_SESION: 'CERRAR_SESION',
  LIMPIAR_IMAGEN_SIGNUP: 'LIMPIAR_IMAGEN_SIGNUP',
  CARGAR_IMAGEN_SIGNUP: 'CARGAR_IMAGEN_SIGNUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dnjmfovqj/image/upload',
  CLOUDINARY_PRESET: ANON.PRESET,
  CARGAR_IMAGEN_PUBLICACION: 'CARGAR_IMAGEN_PUBLICACION',
  LIMPIAR_IMAGEN_PUBLICACION: 'LIMPIAR_IMAGEN_PUBLICACION',
  SUBIR_PUBLICACION: 'SUBIR_PUBLICACION',
  DESCARGAR_PUBLICACIONES: 'DESCARGAR_PUBLICACIONES',
  AGREGAR_PUBLICACIONES_STORE: 'AGREGAR_PUBLICACIONES_STORE',
  AGREGAR_AUTORES_STORE: 'AGREGAR_AUTORES_STORE',
  EXITO_SUBIR_PUBLICACION: 'EXITO_SUBIR_PUBLICACION',
  ERROR_SUBIR_PUBLICACION: 'ERROR_SUBIR_PUBLICACION',
  LIMPIAR_SUBIR_PUBLICACION: 'LIMPIAR_SUBIR_PUBLICACION',
};

export default CONSTANTES;
